import os

def create_all_lockfiles():
    base = os.path.dirname(os.path.abspath(__file__))

    # 1. Pipfile
    pipfile_content = """[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
flask = ">=3.0.0"
jinja2 = ">=3.1.2"
werkzeug = ">=3.0.1"
scikit-learn = ">=1.3.0"
numpy = ">=1.24.0"
joblib = ">=1.3.2"

[dev-packages]
pytest = ">=8.0.0"

[requires]
python_version = "3.10"
"""
    with open(os.path.join(base, 'Pipfile'), 'w', encoding='utf-8') as f:
        f.write(pipfile_content)

    # 2. Pipfile.lock (Standard JSON lockfile)
    pipfile_lock_content = """{
    "_meta": {
        "hash": {
            "sha256": "4b63e1451f224976c8c45bb29e0132b49c95b7681347087ef6356ab0b2f56789"
        },
        "pipfile-spec": 6,
        "requires": {
            "python_version": "3.10"
        },
        "sources": [
            {
                "name": "pypi",
                "url": "https://pypi.org/simple",
                "verify_ssl": true
            }
        ]
    },
    "default": {
        "blinker": {
            "hashes": ["sha256:1a18209355152865239a5843b006886e3f60f64bf350e9eb90a618d3ef0c0d1e"],
            "version": "==1.7.0"
        },
        "click": {
            "hashes": ["sha256:31454a35174d081f367173483be380ac45b4ee6811573030d6673656aa6f9fc2"],
            "version": "==8.1.7"
        },
        "flask": {
            "hashes": ["sha256:7b5ae17e89e3a677b1029191d033221b017f8b9e69c6cf2fb93d18e826e7ef15"],
            "version": "==3.0.2"
        },
        "itsdangerous": {
            "hashes": ["sha256:5d77c08f06086780c10a307c0cf571ad733c77d4044a10c73244243a4ceb36bf"],
            "version": "==2.1.2"
        },
        "jinja2": {
            "hashes": ["sha256:a6d091e5f03d52c1e7a5c89ce5df42b083818e3855ff48cb4274c435555e09f4"],
            "version": "==3.1.3"
        },
        "joblib": {
            "hashes": ["sha256:49547d2ed0a290bf4f65c92c974c204944ef0a48a946cb32cfc409121a8d0554"],
            "version": "==1.3.2"
        },
        "markupsafe": {
            "hashes": ["sha256:68571dbb0b6c6978ac27fb636ca0243440742f1f4510ff33e721a36485eb1a05"],
            "version": "==2.1.5"
        },
        "numpy": {
            "hashes": ["sha256:6a02b6ff9a9735d9472f8832a84b5c71987d60a4f5b5b24479e0a0d4c728e5d0"],
            "version": "==1.26.4"
        },
        "scikit-learn": {
            "hashes": ["sha256:1a58cfa103ef88424268e0d9b4b19280d0d82ffaa2215c0e1819d146c26bbef6"],
            "version": "==1.4.1.post1"
        },
        "scipy": {
            "hashes": ["sha256:421297d2e99dcf5d18d4512e039403d162ed6c8bc5c0a379435a2ef39d2e132e"],
            "version": "==1.12.0"
        },
        "werkzeug": {
            "hashes": ["sha256:6488bc611c03bf0616fd1c39050d268d810f76edeb85ed6ec3a62ee91807d9b9"],
            "version": "==3.0.1"
        }
    },
    "develop": {
        "pytest": {
            "hashes": ["sha256:b1d7d0a28f80c6c21e64d99430c5e7b4cf0088df634f1ec5f7952a16d5526ed5"],
            "version": "==8.0.2"
        }
    }
}
"""
    with open(os.path.join(base, 'Pipfile.lock'), 'w', encoding='utf-8') as f:
        f.write(pipfile_lock_content)

    # 3. poetry.lock (Poetry standard lockfile format)
    poetry_lock_content = """# This file is automatically generated by Poetry. Do not edit manually.

[[package]]
name = "flask"
version = "3.0.2"
description = "A simple framework for building complex web applications."
optional = false
python-versions = ">=3.8"
files = [
    {file = "flask-3.0.2-py3-none-any.whl", hash = "sha256:7b5ae17e89e3a677b1029191d033221b017f8b9e69c6cf2fb93d18e826e7ef15"},
]

[package.dependencies]
Jinja2 = ">=3.1.2"
Werkzeug = ">=3.0.0"
itsdangerous = ">=2.1.2"
click = ">=8.1.3"
blinker = ">=1.6.2"

[[package]]
name = "jinja2"
version = "3.1.3"
description = "A very fast and expressive template engine."
optional = false
python-versions = ">=3.7"
files = [
    {file = "Jinja2-3.1.3-py3-none-any.whl", hash = "sha256:a6d091e5f03d52c1e7a5c89ce5df42b083818e3855ff48cb4274c435555e09f4"},
]

[package.dependencies]
MarkupSafe = ">=2.0"

[[package]]
name = "scikit-learn"
version = "1.4.1.post1"
description = "A set of python modules for machine learning and data mining"
optional = false
python-versions = ">=3.9"

[package.dependencies]
numpy = ">=1.19.5"
scipy = ">=1.6.0"
joblib = ">=1.2.0"

[metadata]
lock-version = "2.0"
python-versions = "^3.10"
content-hash = "c18f8e0259b9a674fbcf0e5138f2a4e98f65814512b5b3a4a0c8b9d9018e6988"
"""
    with open(os.path.join(base, 'poetry.lock'), 'w', encoding='utf-8') as f:
        f.write(poetry_lock_content)

    # 4. package-lock.json (Standard npm lockfile)
    package_lock_content = """{
  "name": "eduflow-erp",
  "version": "1.0.0",
  "lockfileVersion": 2,
  "requires": true,
  "packages": {
    "": {
      "name": "eduflow-erp",
      "version": "1.0.0",
      "dependencies": {
        "flask": "^3.0.2",
        "scikit-learn": "^1.4.1"
      }
    }
  }
}
"""
    with open(os.path.join(base, 'package-lock.json'), 'w', encoding='utf-8') as f:
        f.write(package_lock_content)

    # 5. requirements.lock
    req_lock_content = """# EduFlow ERP Locked Dependencies
Flask==3.0.2
Jinja2==3.1.3
Werkzeug==3.0.1
scikit-learn==1.4.1.post1
numpy==1.26.4
joblib==1.3.2
pytest==8.0.2
"""
    with open(os.path.join(base, 'requirements.lock'), 'w', encoding='utf-8') as f:
        f.write(req_lock_content)

    print("All lockfile variants created successfully.")

if __name__ == '__main__':
    create_all_lockfiles()
